service: aws-nodejs-lambda-starter
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-newrelic-lambda-layers

custom:
  newRelic:
    accountId: YOUR_ACCOUNT_ID
    apiKey: YOUR_API_KEY
    linkedAccount: serverless
    enableExtension: true
    enableIntegration: true
    logEnabled: true
    cloudWatchFilter: "*"
